### ISSUE TITLE
Have a party to celebrate

### ISSUE THREAD

**Issue by dholstius** [holstius/BY2011-methodology#13]
## Issue Description

We should have a party, because:

> _A party without a cake is just a meeting_ — Julia Child

## Checklist

- [x] bake many cakes
- [x] decide on the flavor
- [x] get the ingredients

## Key Requirements

* should be tasty
* should be big

@songbai-BAAQMD Can you comment please? 
@arihusain: Assigning you; please LMK if you don't have time!

**Comment by Emsinv9Michael** [comment]
I will go to Costco to buy cake ingredients: 

- [ ] - flour, 
- [ ] - sugar, 
- [ ] - eggs, 
- [ ] - butter.
